Ledger provider
multiversx/mx-sdk-dapp-core pull request #25
Opened 2024-09-19 14:31 UTC by arhtudormorar

Integrate programatic ledger:
- login
- sign transactions
- sign guarded transactions

2024-09-19 15:43 UTC, andreigiura approved these changes

2024-09-20 06:15 UTC, razvantomegea requested changes

2024-09-20 06:15 UTC, razvantomegea commented on src/core/methods/signTransactions/helpers/getGuardedTransactions.ts
> +  if (!isGuarded || (isGuarded && allSignedByGuardian)) {
if (!isGuarded || allSignedByGuardian)

2024-09-20 06:15 UTC, razvantomegea commented on src/core/methods/signTransactions/helpers/getGuardedTransactions.ts
> +  if (!isGuarded || (isGuarded && allSignedByGuardian)) {
if it is not guarded, of course it is guarded :)

2024-09-20 06:15 UTC, razvantomegea commented on src/core/providers/ProviderFactory.ts
> +          await Promise.all(balancePromises).then((balances) => {
No need for then.
const balances = await Promise.all(balancePromises);

2024-09-23 13:49 UTC, razvantomegea approved these changes

2024-09-23 13:50 UTC, merged